import { serverSideTranslations } from "next-i18next/pages/serverSideTranslations"
import { Geist, Geist_Mono } from "next/font/google"
import Head from "next/head"
import Image from "next/image"
import styles from "@/styles/Home.module.css"
import MainLayout from "@/app/MainLayout"
import localFont from "next/font/local";
import { wrapper } from "@/app/store"
import { accountsApi } from "@/app/store/api/accountsApi"
import { getCookie } from "cookies-next"


const commissioner = localFont({
  src: [
    {
      path: "../styles/fonts/Commissioner-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../styles/fonts/Commissioner-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-commissioner",
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={commissioner.className}>
        <main>
          <MainLayout />
        </main>
      </div>
    </>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async ({ req, res, locale }) => {
    const rawCookies = req.headers.cookie || "";
    // Ищем куку access и забираем только её значение
    const tokenMatch = rawCookies.match(/access=([^;]+)/);
    const token = tokenMatch ? tokenMatch[1] : null;

    if (token) {
      // ПЕРЕДАЕМ СТРОКУ ТОКЕНА
      await store.dispatch(accountsApi.endpoints.retrieveProfile.initiate(token));
    }

    await Promise.all(store.dispatch(accountsApi.util.getRunningQueriesThunk()));
    return {
      props: {
        ...(await serverSideTranslations(locale ?? "ru-RU", ["common"])),
      },
    }
  }
);